#if !canImport(ObjectiveC)
import XCTest

extension Bech32Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Bech32Tests = [
        ("testAddressEncodingDecodingPerfomance", testAddressEncodingDecodingPerfomance),
        ("testInvalidAddress", testInvalidAddress),
        ("testInvalidAddressEncoding", testInvalidAddressEncoding),
        ("testInvalidChecksum", testInvalidChecksum),
        ("testValidAddress", testValidAddress),
        ("testValidChecksum", testValidChecksum),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Bech32Tests.__allTests__Bech32Tests),
    ]
}
#endif
