#if !canImport(ObjectiveC)
import XCTest

extension RPC2Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RPC2Tests = [
        ("testCall", testCall),
        ("testErrorDelegate", testErrorDelegate),
        ("testStress", testStress),
        ("testWsLong", testWsLong),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RPC2Tests.__allTests__RPC2Tests),
    ]
}
#endif
